name: streamlit-app

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - pip
  - libgl
  - libglib
  - numpy=1.26.4
  - pip:
      - streamlit
      - requests
      - python-dotenv
      - Pillow
      - PyMuPDF
      - pandas
      - pytesseract
      - reportlab
      - rapidocr-onnxruntime==1.3.25
      - onnxruntime
      - streamlit-paste-button==0.1.2
