name: app-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - requests
    - python-dotenv
    - Pillow
    - PyMuPDF
    - numpy==1.26.4
    - pandas
    - pytesseract
    - reportlab
    - opencv-python-headless==4.11.0.86
    - rapidocr-onnxruntime==1.3.25
    - streamlit-paste-button
